### ISSUE TITLE
generate_params is not defined anywhere

### ISSUE THREAD

**Issue by Fontanapink** [ucl-cssb/MIMIC#25]
```
        # TODO: generate_params is not defined anywhere
```

https://github.com/ucl-cssb/MIMIC/blob/fd6c9c20d9329b53e04bc922475a254706bedff0/run_gMLV_sims.py#L172

**Comment by cpbarnes** [comment]
This is in Neythen's old code, kept in gMLV_merged. We will need to merge in these functions to gMLV_sim so that run_gMLV_sims.py works

**Comment by cpbarnes** [comment]
These are now in the example file run_gMLV_sims.py
